### ISSUE TITLE
Replace extension

### ISSUE THREAD

**Issue by btecu** [abuiles/ember-101#32]
Since the files contain markdown, should use the extension `md` instead of `txt` so github renders them properly.

**Comment by abuiles** [comment]
Makes sense, I think I was using .txt because leanpub tell us to do so, but it might not be necessary, checking with them.

**Comment by josescasanova** [comment]
Just submitted a PR: https://github.com/abuiles/ember-101/pull/35

**Comment by abuiles** [comment]
Fixed, thanks @josescasanova.

Is important to mention that we are using leanpub's favored MD so a couple of things might not display properly here, the best way is to get the book directly from https://leanpub.com/ember-cli-101.
