### ISSUE TITLE
Update Ember

### ISSUE THREAD

**Issue by julientherier** [abuiles/ember-101#37]
Page 8, we update the `ember` and `ember-data` packages using bower.
But if I look at the `package.json` file, `ember-data` is `1.13.8`.
Do we need to update the `package.json` file too?

**Comment by abuiles** [comment]
@julientherier good call! 

so how it works is that the part in `package.json` is the "addon" part, meaning it takes cares of merging in the ember-data files into the final build, and the `bower.json` download the files which will be "merged". 

Even if the versions are different, the files in the build will be the ones specified in `bower`, non the less I'll add a recommendation to upgrade the package too to avoid confusions.

**Comment by abuiles** [comment]
This has been fixed, thanks!
