### ISSUE TITLE
Utilize GitBook

### ISSUE THREAD

**Issue by wldcordeiro** [abuiles/ember-101#48]
This creates a nice presentation for your book that people can use in-browser.
https://www.gitbook.com/

Examples:
* http://rustbyexample.com/
* http://xgrommx.github.io/rx-book/

**Comment by abuiles** [comment]
Thanks for the suggestion! I started the book in leanpub and would prefer to keep it there for now, I'm checking with them if there is a way to create a web view.

Also when you download the PDF you can keep track of changes easily since you get leanpub's notification.
