### ISSUE TITLE
Page 3 - typo "ambitious web application"

### ISSUE THREAD

**Issue by chillvetica** [abuiles/ember-101#59]
The first sentence in "Why Ember?" reads:

Ember is an evolving JavaScript framework for creating “ambitious web application”,

"applications" should be plural, and the comma should be within the quotes, so it should read  - 

Ember is an evolving JavaScript framework for creating “ambitious web application,”

That's it!

**Comment by abuiles** [comment]
@chillvetica this has been fixed, thanks!
