### ISSUE TITLE
Error getting and creating loans

### ISSUE THREAD

**Issue by rubenmoya** [abuiles/ember-101#71]
I'm in the page 60 aprox of the book (creating loans) and I'm getting this error when I try to access or create a loan. I cloned [this commit](https://github.com/abuiles/borrowers-2016/commit/9b3c3a4230268cf91ee583862163b75f9dbd73d7) and I get the same error.

<img width="521" alt="screen shot 2016-06-12 at 23 08 47" src="https://cloud.githubusercontent.com/assets/905225/15993857/6cf30458-30f3-11e6-8a56-5d22ae33de32.png">

Any ideas?

**Comment by abuiles** [comment]
@rubenmoya hola, parece que hubo un problema temporal con el server, pero ya parece estar funcionado bien, lo acabo de intentar y funciona.

**Comment by rubenmoya** [comment]
Buenos días! Sigue dándome el mismo error.

Cuando accedo directamente a la API si que me devuelve el JSON correctamente.

**Comment by abuiles** [comment]
@rubenmoya hola! cómo estás  corriendo el server? si le estás pasando la opción  proxy? 

Si sí, entonces, puedes intentar clonando este branch https://github.com/abuiles/borrowers-2016/tree/adapter-host  que utiliza la opción de host directamente en el adapter.

**Comment by rubenmoya** [comment]
Así sí que funciona, ahora lo único que no me aparecen los objetos que añado con "Lend Article", pero ya lo investigaré :P 

Gracias!

**Comment by abuiles** [comment]
@rubenmoya entonces el problema parece venir del proxy?

**Comment by rubenmoya** [comment]
@abuiles Sí, tiene toda la pinta, porque ni si quiera he clonado el proyecto, sólo he creado el adapter y he metido el host.

**Comment by abuiles** [comment]
@rubenmoya de pronto puedes intentar con este URL en el proxy (sin el cambio del adapter) https://ember-101.herokuapp.com

`ember server --proxy https://ember-101.herokuapp.com`

**Comment by rubenmoya** [comment]
Nada, no te preocupes, lo pongo en el host, así es más cómodo para iniciar el server :D

**Comment by abuiles** [comment]
Perfecto, gracias :)
