### ISSUE TITLE
API call unsuccessful (site seems down, too)

### ISSUE THREAD

**Issue by jwithington** [abuiles/ember-101#72]
Hello hello!  When I do the very first API call, here's what I get in my terminal:

```
curl https://api.ember-101.com/friends | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
No JSON object could be decoded
```

I tried a curl from another API and got a response, no problem. This seems to be saying that  https://api.ember-101.com/friends is down. Any advice?

Thanks!

**Comment by abuiles** [comment]
@jwithington hi! I just tried and is working ... since it is behind  a heroku app maybe it was starting up? Click here and you'll get the results https://api.ember-101.com/friends
