### ISSUE TITLE
Update/Create loans returns an error in the server

### ISSUE THREAD

**Issue by rubenmoya** [abuiles/ember-101#75]
I'm getting an error in the server when creating or updating a loan.

It's related to the createdAt, it's sent as created-at, I fixed it in the serializer/adapter, so it's send as created_at, but the error still there because it's sent as nil, I removed it from the model in Ember and it works.

I also cloned the server and removing the parameter in the controller actions solves the error too:

```
class LoansController < JSONAPI::ResourceController
  def create
    params["data"]["attributes"].delete("created_at")
    super
  end

  def update
    params["data"]["attributes"].delete("created_at")
    super
  end
end
```

**Comment by abuiles** [comment]
@rubenmoya sorry! I forgot to push this commit which fixed that issue https://github.com/abuiles/borrowers-api/commit/aac7128ad3d16280f5d903117407b8f86d872ec2

Thank should fixed it.

Thanks!
